### ISSUE TITLE
WebSocket Problem

### ISSUE THREAD

**Issue by PsychoHJ** [kevinjycui/EEG-Cursor-Control#2]
Hi Mr.Kevin 
i try to run your app but i have the following issue 

```
Traceback (most recent call last):
  File "C:\Users\Hammody\Desktop\BCI\EEG-Cursor-Control\client.py", line 1, in <module>
    from auth import token
  File "C:\Users\Hammody\Desktop\BCI\EEG-Cursor-Control\auth.py", line 3, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection' from 'websocket' (C:\Users\Hammody\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websocket\__init__.py)
```
i wonder if there any solution to solve this , thank you.

**Comment by kevinjycui** [comment]
Did you install websocket-client? Try doing pip install websocket-client

**Comment by PsychoHJ** [comment]
Yes , i already installed it , even when i try to re-install it 
this is what i see 

```
C:\Users\Hammody\AppData\Local\Programs\Python\Python37-32\Scripts>pip install websocket_client
Requirement already satisfied: websocket_client in c:\users\hammody\appdata\local\programs\python\python37-32\lib\site-packages (0.56.0)
Requirement already satisfied: six in c:\users\hammody\appdata\local\programs\python\python37-32\lib\site-packages (from websocket_client) (1.12.0)
```

**Comment by kevinjycui** [comment]
If you installed websocket, try uninstalling it and then reinstalling websocket-client. I think there is a difference between websocket-client and websocket_client, so try installing websocket-client instead

**Comment by PsychoHJ** [comment]
i already did this and got this error 

```
Traceback (most recent call last):
  File "client.py", line 1, in <module>
    from auth import token
  File "C:\Users\Hammody\Desktop\BCI\EEG-Cursor-Control\auth.py", line 3, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection' from 'websocket' (C:\Users\Hammody\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websocket\__init__.py)
```

**Comment by kevinjycui** [comment]
Make sure you install **websocket-client** and not **websocket_client**. I am very sure that these two are different packages. Also, if you haven't already, install websocket. Uninstall and reinstall these to be sure. Here are the requirements concerning WebSockets:
```
websocket==0.2.1
websocket-client==0.54.
```

**Comment by kevinjycui** [comment]
This may seem redundant but try uninstalling websocket and then reinstalling websocket-client again. If that doesn't work, try installing websocket-client2 instead.

**Comment by Hayhat95** [comment]
Hi Mr.Kevin
can you help me with this error Please

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time,

**Comment by kevinjycui** [comment]
@Hayhat95 This is likely due to a network issue between your PC and the server. May have something to do with a proxy. 

As per the original issue, make sure that you do not have any python files named websocket (pip uninstall all your websocket modules such as websocket, websockets, etc. and only install websocket-client). 

Nonetheless, as Emotiv has updated to Cortex V2, any connection to the url in this project will not go through anyway, and you should change the url to `wss://localhost:6868`. There are other updates as well, including logging on through Emotiv's App instead of just using the websocket to log in. These changes can be found in the Cortex V2 [release notes](https://emotiv.gitbook.io/cortex-api/release-notes#changes-from-cortex-1-x-to-cortex-v-2-0). 

Furthermore, as there are a large number of changes required to make this project Cortex V2 compatible, and I have moved on from this project, I will not be intending to update it in the foreseeable future. If you are interested, [here](https://github.com/Emotiv/cortex-v2-example/blob/master/python/lib/cortex.py) is another Emotiv project that does everything this project does in a way that is compatible with Cortex V2 (except for the applications with pyautogui).

**Comment by Hayhat95** [comment]
Ok thank you for the information
But when i connected to client side on web browser it is ok. I just have
problem in python code i will seeing the module maybe it is the problem and
thank you again for your help

**Comment by Hayhat95** [comment]
And i use cortex V2 i have just a problem in python but in clinet side over
web browser plug in everything is ok

**Comment by Hayhat95** [comment]
Greetings I am doing a job with the 5-channel Emotiv Insight device I am
using cortex v2 to extract the data such as mental commands and gyroscope,
I have no problems at the time of creating cortex session and data
subscription apparently but I do not throw the values ​​in In the case of
the gyroscope I am using the following code in python

import json
from websocket import create_connection
import ssl
import time
import pyautogui

thought = ""
token =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5yaWNrc2Fuc29tLmRhdG9zZW1vdGl2IiwiYXBwVmVyc2lvbiI6IjEuMCIsImV4cCI6MTU2NTU1MDYxMSwibGljZW5zZUlkIjoiYTQxZDJkYzAtZWE1OS00ZDFhLWIwNTctODNkYWU1ZmJmZmM4IiwibmJmIjoxNTY1MjkxNDExLCJ1c2VySWQiOiI5Y2FiYTc5NS0yYTM2LTRlNWItOTJmNC1lMjYwZWNiYWUwMmQiLCJ1c2VybmFtZSI6InJpY2tzYW5zb20iLCJ2ZXJzaW9uIjoiMi4wIn0=.2fVCZY0aKOkKVwgHf7E4REQMPXDccRDhln3kUbPvAus="

print("Connecting a websocket...")
receivedData = create_connection("wss://localhost:6868",
sslopt={"cert_reqs": ssl.CERT_NONE})

#------------------------------------------------------------------------
print("Revisa la conectividad con el auricular")
receivedData.send(json.dumps({
"jsonrpc": "2.0",
"method": "queryHeadsets",
"params": {},
"id": 1
}))

print(receivedData.recv())

#------------------------------------------------------------------------
print("Crear sesion")

receivedData.send(json.dumps({
"id": 1,
"jsonrpc": "2.0",
"method": "createSession",
"params": {
"cortexToken": token,
"headset": "INSIGHT-A1D201D2",
"status": "open"
}}))

#print(receivedData.recv())

idses=json.loads(receivedData.recv())["result"]
print(idses['id'])

#------------------------------------------------------------------------
print("\nSubscripcion de datos")

receivedData.send(json.dumps({
"id": 1,
"jsonrpc": "2.0",
"method": "subscribe",
"params": {
"cortexToken": token,
"session": idses['id'],
"streams": ["mot"]
}
}))

while (True) :

          print(receivedData.recv())

I get the following results

It just print subscribe successfully to mot stream and then nothing happens
it doesn't get the value of my headsets motions

[image: image]
<https://user-images.githubusercontent.com/47214435/62811393-15e38000-bac7-11e9-9d5f-df3e581057c8.png>

**Comment by kevinjycui** [comment]
It seems like you're printing the received data immediately after sending a request to the WebSocket for the subscription data. Try receiving the subscription data for the subscription data (like how you do with the create session/query headset data) before trying to receive the gyroscopic/mental command data.

**Comment by Hayhat95** [comment]
I do it but i just receive successfully to stream "com"
And then my program stay running and i didn't get mental commands
But in online clinet i get after thet the values of mental commands

**Comment by Hayhat95** [comment]
I use cortex V2
And i use websocket
